### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by amogus07** [PipInSpace/rDex-UI#1]
Trying to run it with `RUST_BACKTRACE=full cargo run`, the window opens but then closes again. Output:
```Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/rdex-ui`
thread '<unnamed>' panicked at src/main.rs:26:10:
Failed to start shell process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x55fb94ae7b6c - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fb94ae7b6c - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fb94ae7b6c - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55fb94ae7b6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fb94b11f3c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55fb94b11f3c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55fb94ae4d3e - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55fb94ae7954 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fb94ae7954 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fb94ae9163 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55fb94ae8e84 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55fb94ae96e5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55fb94ae95e1 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55fb94ae8096 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55fb94ae9332 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55fb941f2c35 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55fb941f3203 - core::result::unwrap_failed::h8c4b86241881fbbb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
  17:     0x55fb94465095 - core::result::Result<T,E>::expect::h2985fae093ed010b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1034:23
  18:     0x55fb9425edd4 - rdex_ui::terminal::hb216991bcf299f36
                               at /home/konstantink/src/rDex-UI/src-tauri/src/main.rs:21:19
  19:     0x55fb941f8c72 - rdex_ui::main::{{closure}}::{{closure}}::h6821562a935b2928
                               at /home/konstantink/src/rDex-UI/src-tauri/src/main.rs:121:35
  20:     0x55fb9437f716 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b7296f8ba156d9d
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:154:18
  21:     0x55fb94215a03 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hdb25c23159071b38
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/mod.rs:529:17
  22:     0x55fb9429c813 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h05ff39f55e77489a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  23:     0x55fb9431e7ef - std::panicking::try::do_call::he791e8871c3e44be
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  24:     0x55fb94322ebb - __rust_try
  25:     0x55fb9431ca58 - std::panicking::try::hdb48c029c70dd41f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  26:     0x55fb94215811 - std::panic::catch_unwind::h1f63687d11b8a9c7
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  27:     0x55fb94215811 - std::thread::Builder::spawn_unchecked_::{{closure}}::h74f7674a48034231
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/mod.rs:528:30
  28:     0x55fb9435272e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf75ea9f84308a89
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  29:     0x55fb94aedc25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa37c25e0ad051b0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  30:     0x55fb94aedc25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9486bed8ab2e65ad
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
  31:     0x55fb94aedc25 - std::sys::unix::thread::Thread::new::thread_start::hd28b46dbf5673d17
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7f4da314b897 - start_thread
  33:     0x7f4da31d26bc - clone3
  34:                0x0 - <unknown>
dir send to terminal
thread 'main' panicked at src/main.rs:16:28:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x55fb94ae7b6c - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fb94ae7b6c - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fb94ae7b6c - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55fb94ae7b6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fb94b11f3c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55fb94b11f3c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55fb94ae4d3e - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55fb94ae7954 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fb94ae7954 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fb94ae9163 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55fb94ae8e84 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55fb94ae96e5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55fb94ae95e1 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55fb94ae8096 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55fb94ae9332 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55fb941f2c35 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55fb941f3203 - core::result::unwrap_failed::h8c4b86241881fbbb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
  17:     0x55fb944660d5 - core::result::Result<T,E>::unwrap::hf432e7af77367deb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
  18:     0x55fb94262562 - rdex_ui::send_terminal::h90142badf99a6d15
                               at /home/konstantink/src/rDex-UI/src-tauri/src/main.rs:16:5
  19:     0x55fb941f9148 - rdex_ui::main::{{closure}}::h126194ba4cafd165
                               at /home/konstantink/src/rDex-UI/src-tauri/src/main.rs:126:25
  20:     0x55fb942e0087 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h947d60513fd4e68f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  21:     0x55fb942c6db5 - tauri::manager::WindowManager<R>::run_invoke_handler::he3b938f60bc19c03
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/manager.rs:929:5
  22:     0x55fb9424a796 - tauri::window::Window<R>::on_message::h6b769a3b74c8225f
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/window.rs:1610:11
  23:     0x55fb942c71df - tauri::manager::WindowManager<R>::prepare_ipc_handler::{{closure}}::he9bdc0b485f0232d
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/manager.rs:617:19
  24:     0x55fb942e01c3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he34e7dcaa698e3d4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  25:     0x55fb9420cf6c - tauri_runtime_wry::create_ipc_handler::{{closure}}::ha35e45fbcc6536a1
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.1/src/lib.rs:3324:5
  26:     0x55fb944e1b02 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha88759eeb8c22139
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  27:     0x55fb944e1b02 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha88759eeb8c22139
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
  28:     0x55fb944ea7ec - wry::webview::webkitgtk::InnerWebView::new::{{closure}}::hcedafa8e20e69789
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wry-0.24.4/src/webview/webkitgtk/mod.rs:94:11
  29:     0x55fb944fd653 - <O as webkit2gtk::auto::user_content_manager::UserContentManagerExt>::connect_script_message_received::script_message_received_trampoline::h759b4aa0b6961e7d
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webkit2gtk-0.18.2/src/auto/user_content_manager.rs:299:7
  30:     0x7f4da59de52a - g_closure_invoke
  31:     0x7f4da5a0cfec - <unknown>
  32:     0x7f4da59fdd59 - <unknown>
  33:     0x7f4da59fdf91 - g_signal_emit_valist
  34:     0x7f4da59fe053 - g_signal_emit
  35:     0x7f4da68ab893 - <unknown>
  36:     0x7f4da694112d - <unknown>
  37:     0x7f4da6437312 - <unknown>
  38:     0x7f4da6436898 - <unknown>
  39:     0x7f4da66e6cf9 - <unknown>
  40:     0x7f4da67f89ff - <unknown>
  41:     0x7f4da66de36a - <unknown>
  42:     0x7f4da66e048a - <unknown>
  43:     0x7f4da4cac095 - <unknown>
  44:     0x7f4da4d02e4d - <unknown>
  45:     0x7f4da4d0383d - <unknown>
  46:     0x7f4da33dbe5c - <unknown>
  47:     0x7f4da3436dd8 - <unknown>
  48:     0x7f4da33d9ad3 - g_main_context_iteration
  49:     0x7f4da5406e0d - gtk_main_iteration_do
  50:     0x55fb94626742 - gtk::auto::functions::main_iteration_do::h71c64cc32bb839d6
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.15.5/src/auto/functions.rs:405:24
  51:     0x55fb943400e4 - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}::h12b2bb8233c83166
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:1060:11
  52:     0x55fb9422a201 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::hf143b40ec0c94730
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.15.12/src/main_context.rs:156:12
  53:     0x55fb9433fafe - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h909ffc7088609b53
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:958:5
  54:     0x55fb94340ebd - tao::platform_impl::platform::event_loop::EventLoop<T>::run::h27334d70e7bb286c
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:912:21
  55:     0x55fb9421e329 - tao::event_loop::EventLoop<T>::run::h6072b82ded70ad2c
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/event_loop.rs:179:5
  56:     0x55fb9420e38b - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::h78de4a33a5ad519c
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.1/src/lib.rs:2256:5
  57:     0x55fb9433bc6b - tauri::app::App<R>::run::h9f080036ec5326cd
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/app.rs:875:5
  58:     0x55fb9433bfda - tauri::app::Builder<R>::run::h3737bd10f8396225
                               at /home/konstantink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/app.rs:1724:5
  59:     0x55fb94261a06 - rdex_ui::main::h7512fba4777f54ce
                               at /home/konstantink/src/rDex-UI/src-tauri/src/main.rs:117:5
  60:     0x55fb94352a9b - core::ops::function::FnOnce::call_once::h18720cbad511f089
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  61:     0x55fb9437f6ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h6d776ff5e3ab68c1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:154:18
  62:     0x55fb94273651 - std::rt::lang_start::{{closure}}::ha0e766578ba0940e
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:166:18
  63:     0x55fb94ae044b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
  64:     0x55fb94ae044b - std::panicking::try::do_call::h629e203a624883e4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  65:     0x55fb94ae044b - std::panicking::try::h7b61614724d6a4f1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  66:     0x55fb94ae044b - std::panic::catch_unwind::h354ac1c0268491d8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  67:     0x55fb94ae044b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
  68:     0x55fb94ae044b - std::panicking::try::do_call::h54583f67455bff32
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  69:     0x55fb94ae044b - std::panicking::try::hb0e12c4e01d39dc2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  70:     0x55fb94ae044b - std::panic::catch_unwind::h367b6339e3ca9a3b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  71:     0x55fb94ae044b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  72:     0x55fb9427362a - std::rt::lang_start::h8adaf4e0d507b362
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:165:17
  73:     0x55fb942625ce - main
  74:     0x7f4da30e514a - __libc_start_call_main
  75:     0x7f4da30e520b - __libc_start_main_impl
  76:     0x55fb941f35b5 - _start
  77:                0x0 - <unknown>
```

**Comment by VioletSpace** [comment]
I've got an idea what might be going on. It's not that hard to debug, but I suspect you are running a linux machine? Currently the "terminal" process is hard-coded to use the windows cmd (Because this was a quick and dirty mock-up on my windows machine)

`src_tauri/src/main.rs:`
![image](https://github.com/PipInSpace/rDex-UI/assets/79136709/4b261131-c302-4ade-b336-36083932111b)
You could try changing the command program to a linux compatible shell of your liking. 

If you are running this on a windows machine, then I really don't know what could be going wrong. 
I will keep this open until I make the spawned shell dynamic.

**Comment by amogus07** [comment]
You're correct! I'm running Fedora 39. Changing the value from "cmd" to "zsh" did stop the crash and the error message, but I can't really get any further. Running commands, I don't get any output, the command I entered simply disappears. But I suppose this is expected since the project is WIP.
